version: '3.1'
services:

    planner-web:
        image: odoo:13.0
        container_name: planner-testing
        restart: always
        depends_on:
            - db
        ports:
            - "8079:8069"
        volumes:
            - planner_web_data:/var/lib/odoo
            - ./config:/etc/odoo
            - #myextra_addons_folder:/mnt/extra-addons/planner
        environment:
            - PASSWORD_FILE=/run/secrets/postgresql_password
        secrets:
            - postgresql_password

    db:
        image: postgres:14.5-alpine
        container_name: planner-database
        restart: always
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
            - POSTGRES_USER=odoo
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - planner_db_data:/var/lib/postgresql/data/pgdata
        secrets:
            - postgresql_password
  
    pgadmin:
        image: dpage/pgadmin4:7
        # restart: always
        depends_on:
            - db
        environment:
            - PGADMIN_DEFAULT_EMAIL=oscar_prueba@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=testing123
        ports:
            - 5051:80
        volumes:
            - plan_pgadmin_data:/var/lib/pgadmin

volumes:
    planner_web_data:
    planner_db_data:
    plan_pgadmin_data:

secrets:
  postgresql_password:
    file: odoo_pg_pass